### ISSUE TITLE
CPU memory crash

### ISSUE THREAD

**Issue by Eric-chuan** [oppo-us-research/NeuRBF#10]
while initializing kc0, it takes up all CPU memory(125G),and the program will crash. Are there any suggestions to resolve this issue?
<img width="537" alt="image" src="https://github.com/oppo-us-research/NeuRBF/assets/45691282/ddace830-bb2e-491b-a51a-401e947ae364">

**Comment by Eric-chuan** [comment]
i have tried to set the [query_chunked](https://github.com/oppo-us-research/NeuRBF/blob/3b93f4c44b4300d7687e1e5cd1cc370d346984ba/util_clustering.py#L165C38-L165C38) chunk_size  to 1e2, CPU memory still grows to crush.

**Comment by zjp-shadow** [comment]
I have the same error

**Comment by LansburyCH** [comment]
Please try the latest code, I've made some updates to reduce CPU memory usage. When testing on a desktop computer with 64GB RAM, I did not encounter the program being killed issue with the updated code.

**Comment by Eric-chuan** [comment]
This problem has been solved after the code update, so close this issue.

**Comment by Eric-chuan** [comment]
This problem has been solved after the code update, so close this issue.
