### ISSUE TITLE
Question about ASG

### ISSUE THREAD

**Issue by ingra14m** [oppo-us-research/NeuRBF#12]
Hi, thank you for your outstanding job. 

I was very surprised that the author used ASG, as it is a structure that I have been trying to use unsuccessfully. I would like to ask about the actual impact of ASG, because when I tried replacing SGRender with ASGRender in TensoRF, the results rendered directly through ASG tended to produce some strange colors.

**Comment by LansburyCH** [comment]
From my understanding, ASG is like applying RBFs on the view direction domain. It helps the modeling of view-dependent appearance when training images have sufficient coverage of view directions. I guess the problem you encountered is probably related to sparse coverage of view directions, but I'm not sure. May I know how your training data look like?

**Comment by ingra14m** [comment]
Thank you to the author for patiently answering my questions in private. I have now resolved my issue.
