### ISSUE TITLE
export mesh?

### ISSUE THREAD

**Issue by zhouilu** [oppo-us-research/NeuRBF#14]
support to extract mesh from image?

**Comment by LansburyCH** [comment]
For a trained NeRF model on the Synthetic NeRF dataset, you can run the following to export mesh
```python main_nerf.py --config configs/nerf_tensorf/nerf_synthetic.py --data_name lego --ckpt [path_to_checkpoint] --export_mesh 1```
You need to specify ```[path_to_checkpoint]``` and adjust ```data_name``` accordingly.

**Comment by zhouilu** [comment]
> For a trained NeRF model on the Synthetic NeRF dataset, you can run the following to export mesh `python main_nerf.py --config configs/nerf_tensorf/nerf_synthetic.py --data_name lego --ckpt [path_to_checkpoint] --export_mesh 1` You need to specify `[path_to_checkpoint]` and adjust `data_name` accordingly.
thanks
