### ISSUE TITLE
Is that possible using this non-grid-based method for angular space?

### ISSUE THREAD

**Issue by bearprin** [oppo-us-research/NeuRBF#16]
Hi

Thanks for your impressive work.

I have some questions about the method.

As the non-grid-based method, is that possible to use this method in the angular space? Since this space is hard to design a suitable grid.

For example, is that possible to encode the ray dir. of NeRF rather than using SH encoding?

Looking forward to your reply.

**Comment by LansburyCH** [comment]
Yes, it is possible. Actually, Spherical Gaussian is a good non-grid example for ray-space encoding. Our method can be similarly adapted to ray space, with some modification to parameterization and function type.

**Comment by bearprin** [comment]
Thanks for your reply!

Your response has resolved my issue.
