### ISSUE TITLE
Are you planning to release the code of K-planes version of NeRF?

### ISSUE THREAD

**Issue by StarsTesla** [oppo-us-research/NeuRBF#2]
This is very important to me to understand the pratical implementation and details of the paper

**Comment by LansburyCH** [comment]
Yes, we are working on it.

**Comment by StarsTesla** [comment]
Under my understanding, the hybrid version is to : 
1st. sample points X along the ray; 
2nd. for one point of pointset, sample the nearst neighbor points; 
3rd. interpolate the feature of the neighbor points by grid features;
4th. cal the weighted sum of the X's features

Am I right?

@LansburyCH

**Comment by StarsTesla** [comment]
Thanks for that
