### ISSUE TITLE
can NeuRBF  support  LLFF  , Mip-NeRF 360 dataset ?

### ISSUE THREAD

**Issue by goometasoft** [oppo-us-research/NeuRBF#3]
thank your NeuRBF, i like it very much!

can NeuRBF  support  LLFF  , Mip-NeRF 360 dataset ?

**Comment by LansburyCH** [comment]
NeuRBF can support LLFF dataset, which is the version that uses K-Planes as the grid-based part (page 8 bottom right in the NeuRBF paper). We are working on releasing that part of codes. For Mip-NeRF 360 dataset, we have not tried it.
