### ISSUE TITLE
坐标系问题

### ISSUE THREAD

**Issue by wangguangyuan** [oppo-us-research/NeuRBF#5]
你好，感谢开源这么棒的工作，有个问题想请教一下，咱们code里的坐标系是不是opencv坐标系，我看和nerf里的不太一样

**Comment by LansburyCH** [comment]
你好，我们是使用的tensorf的dataloader，tensorf应该是opencv坐标系（see this [post](https://github.com/apchenstu/TensoRF/issues/46#issuecomment-1369592286)）
