### ISSUE TITLE
Error Map for NeRF?

### ISSUE THREAD

**Issue by jyuan-dev** [oppo-us-research/NeuRBF#6]
Excellent work! Great Contribution!

Do you have any comparison on view synthesis compared with e.g. Instant-NGP? as Error map has been made to compare with INGP on 2D image fitting.

Best Regards

**Comment by LansburyCH** [comment]
Hi penguinflys,

Yes, we have compared with Instant-NGP on view synthesis in our paper, supplementary and video. However, we did not compare error maps since we found RGB images are more effective in showing the quality difference in this task.

**Comment by jyuan-dev** [comment]
Thanks, I will find the error map later.
