### ISSUE TITLE
Errors in reloading ckpt.th

### ISSUE THREAD

**Issue by ingra14m** [oppo-us-research/NeuRBF#8]
During the mesh export phase, a reload issue arises, with errors occurring at [L66](https://github.com/oppo-us-research/NeuRBF/blob/c926c287df56dc41664e3acd19506f27fee0114d/main_nerf.py#L66C46-L66C46) I believe this is due to a discrepancy between the imported parameters and the stored parameters.

**Comment by LansburyCH** [comment]
Currently, we have not updated the export_mesh function to work with RBF models. We may add this support later.

**Comment by LansburyCH** [comment]
The export_mesh function has been updated and now works with RBF models.
